name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Install Playwright Browsers
      run: npx playwright install

    - name: Install xvfb
      run: sudo apt-get install -The issue causing the job to fail is that the Playwrighty xvfb

    - name: Run tests with xvfb
      run: xvfb browser executable is missing. This is evident in-run --auto-servernum -- npm test
